name: Deploy Bot to EC2
on:
  push:
    branches: [ "main" ]
    paths: 
      - '**.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to EC2 using rsync
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude='.git' --exclude='config.json'
        path: .
        remote_path: /home/ec2-user/SCinet/SCinetBot
        remote_host: ${{ secrets.EC2_HOST }}
        remote_user: ec2-user
        remote_key: ${{ secrets.EC2_SSH_KEY }}
    
    - name: Restart Telegram bot
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/ec2-user/SCinet/SCinetBot
          sudo systemctl stop tg.service
          sleep 5
          sudo systemctl daemon-reload
          sudo systemctl enable tg_bot.service
          sudo systemctl start tg_bot.service
          sudo systemctl status tg_bot.service --no-pager